# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  cedreo-interactive.com:
    site_hosts:
      - canonical: cedreo-interactive.wabdesign.fr
        # redirects:
        #   - otherdomain.com
    local_path: ../cedreo-interactive # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wab/c-ntrctv.git # replace with your Git repo URL
    #repo_subtree_path:  # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true

  cedar-architect.com:
    site_hosts:
      - canonical: cedar-architect.wabdesign.fr
      - canonical: cedar-architect-fr.wabdesign.fr
        # redirects:
        #   - otherdomain.com
    local_path: ../cedar-architect # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wab/c-rchtct.git # replace with your Git repo URL
    #repo_subtree_path:  # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
      hsts_include_subdomains: false
    cache:
      enabled: true

  cedreo-homeplanner.com:
    site_hosts:
      - canonical: cedreo-homeplanner.wabdesign.fr
        # redirects:
        #   - otherdomain.com
    local_path: ../cedreo-homeplanner # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wab/c-hmplnnr.git # replace with your Git repo URL
    #repo_subtree_path:  # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true

  cedar-studio.com:
    site_hosts:
      - canonical: cedar-studio.wabdesign.fr
        # redirects:
        #   - otherdomain.com
    local_path: ../cedar-studio # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wab/c-std.git # replace with your Git repo URL
    #repo_subtree_path:  # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
